services:
  - type: web
    name: pro-investor-api
    env: node
    plan: free
    # Build jarayoni npx orqali nest build ishlatadi
    buildCommand: npm install && npx nest build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: POSTGRES_URL
        value: postgresql://pro_investor_user:x0FkKkpj312IC4cOTiMcLiUScHUWRwNH@dpg-d36dnljipnbc739387e0-a.oregon-postgres.render.com/pro_investor
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "465"
      - key: SMTP_USER
        value: proinvestorverify@gmail.com
      - key: SMTP_PASS
        value: knhpejvazenvlswu
      - key: JWT_SECRET
        value: super_secret_key
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: APP_PORT
        value: "5000"
